name: Initialize Full Progress Log (Python)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  init-progress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # ✅ 모든 git 이력 가져오기 (중요!)

      - name: Build initial progress log
        run: |
          # 기존 Progress Log 제거
          sed -i '/# 📈 Progress Log/,$d' README.md

          echo "" >> README.md
          echo "# 📈 Progress Log" >> README.md
          echo "| Date | Problems Added | Total |" >> README.md
          echo "|------|----------------|--------|" >> README.md
          
          total=0
          git log --reverse --pretty=format:"%ad" --date=short -- '**/*.py' | sort | uniq -c > tmp.log

          while read count date; do
            total=$((total + count))
            echo "| $date | 🟢 $count | $total |" >> README.md
          done < tmp.log

          echo "" >> README.md
          echo "> **🎯 Total:** $total problems solved" >> README.md
          rm tmp.log

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Initialize full Progress Log (Python)"
          git push
